runtime: python
env: flex
entrypoint: gunicorn main:app --worker-class aiohttp.worker.GunicornWebWorker

runtime_config:
    python_version: 3

api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
